name: CD (Continuous Delivery)

on:
  push:
    branches:
      - develop

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run test

  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build DNR Rules
        run: npm run build:dnr

      - name: Build Extension
        run: npm run build

      - name: Install Playwright Browsers & Deps
        run: npx playwright install chromium --with-deps

      - name: Run E2E Tests
        run: xvfb-run npm run test:e2e
